version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: cp .env.sample .env
      - run: docker-compose up -d
      - run: docker-compose exec backend pylava backend
