version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-node
    steps:
      - checkout

      - restore_cache:
           key: deps-{{ checksum "setup.py" }}-{{ checksum "package.json" }}
      - run:
          name: Install python and node dependencies
          command: make install
      - save_cache:
            key: python-deps-{{ checksum "setup.py" }}
            paths:
              - .venv
              - node_modules

      - run: make tests
      - run: npm run build

      - persist_to_workspace:
          root: .
          paths: dist
