version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-node
    steps:
      - checkout
      - restore_cache:
           key: {{ checksum "requirements.txt" }}
      - run: python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt
      - restore_cache:
           key: {{ checksum "requirements.txt" }}
           paths:
             - "venv"
